#ifndef __PORT_H
#define __PORT_H
#include "main.h"
#define PORT_SENSOR GPIOA
#define CAMBIEN_2 GPIO_PIN_8
#define CAMBIEN_3 GPIO_PIN_9
#define CAMBIEN_5 GPIO_PIN_10
#define PORT_SENSOR1 GPIOE
#define CAMBIEN_4 GPIO_PIN_8
#define CAMBIEN_1 GPIO_PIN_8
#define PORT_NUTNHAN GPIOC
#define NUTNHAN_1 GPIO_PIN_5
#define NUTNHAN_2 GPIO_PIN_6
#define NUTNHAN_3 GPIO_PIN_7
#endif